### ISSUE TITLE
Install Location not valid, Plugin not working

### ISSUE THREAD

**Issue by jordantomax** [mattmcmanus/select-group-layers-sketch-plugin#4]
Hi there, awesome plugin idea, really psyched to use it. However, it's not working! 

The install location that you've written does not exist on my machine, which may be the problem. My plugins appear to be located in ~/Library/Application Support/com.bohemiancoding.sketch3/Plugins. I've tried placing the "Select Group Layers.sketchplugin" file in there and restarting, but no dice. Help!

**Comment by mattmcmanus** [comment]
Bummer! Why not give this a try and let me know if it works:

1. Download the repo and extract it so that you have a folder named `select-child-layers-sketch-plugin`
2. Go to Sketch, click the menu `Menu > Reveal Plugins Folder...`
3. Drag the `select-child-layers-sketch-plugin` folder into the revealed plugin folder

Hopefully that'll do it.

**Comment by jordantomax** [comment]
Well shucks, thought for sure that I'd tried that, but apparently not. Works as expected, thanks!

**Comment by mattmcmanus** [comment]
![](http://media.giphy.com/media/ejK2NEJQFG9fW/giphy.gif)

Thanks for letting me know. I'll update the readme.
